bindAddr = "0.0.0.0"
bindPort = 7000
#kcpBindPort = 7000
quicBindPort = 7000

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
transport.tls.force = false

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
webServer.pprofEnable = false

log.to = "./frps.log"
# trace, debug, info, warn, error
log.level = "error"
log.maxDays = 1
log.disablePrintColor = false

auth.method = "token"
auth.token = "12345678"

# Only allow frpc to bind ports you list. By default, there won't be any limit.
allowPorts = [
  { start = 1, end = 65535 }
]

maxPortsPerClient = 0
udpPacketSize = 1500
natholeAnalysisDataReserveHours = 24